### ISSUE TITLE
evil-mode

### ISSUE THREAD

**Issue by e-carlin** [biviosoftware/home-env#14]
Add evil-mode to home-env. Enable with M-x evil-mode. Figure out how hooks work so I can add hooks like map jj to ESC only once evil-mode is enable and the configuration is unloaded when it is disabled.

**Comment by moellep** [comment]
evil-mode sounds like the path to the dark-side.

**Comment by robnagler** [comment]
Martin once programmed this alias:

`alias vi='echo adapt or die'`

I'll maybe do that for m-x evil-mode ;-)
