### ISSUE TITLE
emacs: Run pykern.pkcli.fmt.run on vc-diff and fmt.check on vc-commit

### ISSUE THREAD

**Issue by robnagler** [biviosoftware/home-env#37]
I almost always run one or the other in emacs so it would be convenient. Alternatively, could create a new command that is used in place for git commit in emacs and in the shell that runs a check.

**Comment by e-carlin** [comment]
Should we add a git commit hook which would work for everyone on the team?

**Comment by robnagler** [comment]
I want it to happen before the commit. I also have my suspicions about hooks, but I forgot why. Feel free to experiment if they meet the goal of failing a commit.

**Comment by robnagler** [comment]
fixed by always running fmt on save
