### ISSUE TITLE
20221231 bivio-git-push should know push to remote branch

### ISSUE THREAD

**Issue by robnagler** [biviosoftware/home-env#41]
To avoid:

```txt
fatal: The current branch 276-pyenv-path has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin 276-pyenv-path
```

**Comment by e-carlin** [comment]
I've been using this for a couple years with no (known) problems

```bash
function gp() {
    if git push "$@" ; then
        return
    fi
    local b=$(git rev-parse --abbrev-ref HEAD)
    if ! git config --get "branch.$b.merge" ; then
        git push --set-upstream origin "$b"
    fi
}
export -f gp
```

**Comment by robnagler** [comment]
I know think this is a broader issue. We have different operations:

* Create a branch from an issue and push it  -- sometimes we want to create the issue at the same time (for quick fixes)
* Create a PR
* Pull master and delete the branch

There may be other operations. I think we could do the PR from the command line, which would be handy. The other two need to be done from the command line.

I changed the subject line to refer to this. Perhaps this needs to be in Python (middle step).

**Comment by e-carlin** [comment]
GH has a CLI that may be of use https://cli.github.com/ . I've tried it briefly once before but didn't find it that useful.

If there is any appetite besides me I'd also like to consider reviewing PR's from the command line.

**Comment by robnagler** [comment]
I would love to review PRs in emacs.
