### ISSUE TITLE
20221031 emacs goto-error-at-point for python

### ISSUE THREAD

**Issue by robnagler** [biviosoftware/home-env#46]
Go to the file at point from something like this:

`File "/home/vagrant/src/radiasoft/sirepo/sirepo/auth/__init__.py", line 394,`

It could be flexible, but even just parsing this would be good enough. Visit the buffer if already open then go to that line.

**Comment by e-carlin** [comment]
https://github.com/biviosoftware/home-env/blob/88603f460840ca308678d062992a85eb92840bc8/emacs.d/bivio-init.el#L365

**Comment by e-carlin** [comment]
I lifted that code from evil before we had evil in our config. It looks like there has been an update which adds columns too https://github.com/emacs-evil/evil/blob/8325ba0deeca0953b7957485d33de2188b6ded67/evil-commands.el#L3639 . 

The emacs wiki also has another solution https://www.emacswiki.org/emacs/FindFileAtPoint#h5o-6 . Maybe [enabling ffap-bindings](https://github.com/emacs-mirror/emacs/blob/395119998574051e53d466d55136d3e6498e90ef/lisp/ffap.el#L38) and using that would work well.

**Comment by robnagler** [comment]
Perfect, thanks! I looked at ffap and didn't see that.  I should have looked at evil.
