### ISSUE TITLE
Create ability to source scripts from projects

### ISSUE THREAD

**Issue by e-carlin** [biviosoftware/home-env#87]
I have some scripts I wrote that are probably worth sharing.

**Comment by robnagler** [comment]
Should this be in sirepo?

**Comment by e-carlin** [comment]
If you want them to be?

In my personal config https://git.sr.ht/~e-carlin/home-env/tree/master/item/bashrc.d/zz-20-dev.sh#L10 I like to be able to type `sirepo_` in my shell and then have tab completion help me remember what they are named.

**Comment by robnagler** [comment]
It is an interesting question whether we can add a dot file that's search for by zz-20-dev.sh. I am thinking that it might be easier to maintain that way.

**Comment by e-carlin** [comment]
That sounds good

**Comment by e-carlin** [comment]
We ended up just using pkcli https://github.com/radiasoft/sirepo/pull/6369
